// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKrdXTl-0yZAtrp92DjZlLvgEEsYvM8g',
    appId: '1:831728985527:web:1e4f202672c8c31918b432',
    messagingSenderId: '831728985527',
    projectId: 'vandi-88280',
    authDomain: 'vandi-88280.firebaseapp.com',
    storageBucket: 'vandi-88280.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK4Hw-2vdX8Gli4m-iMJRrkXOsEG-QDck',
    appId: '1:831728985527:android:8f633f4064c7990418b432',
    messagingSenderId: '831728985527',
    projectId: 'vandi-88280',
    storageBucket: 'vandi-88280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyWJ-chFa1f2vE2oIFhU4ii1-7rpZVfc',
    appId: '1:831728985527:ios:4e193c52131cf3a618b432',
    messagingSenderId: '831728985527',
    projectId: 'vandi-88280',
    storageBucket: 'vandi-88280.appspot.com',
    iosBundleId: 'com.example.vandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyWJ-chFa1f2vE2oIFhU4ii1-7rpZVfc',
    appId: '1:831728985527:ios:312dcef2b8533a6918b432',
    messagingSenderId: '831728985527',
    projectId: 'vandi-88280',
    storageBucket: 'vandi-88280.appspot.com',
    iosBundleId: 'com.example.vandi.RunnerTests',
  );
}
